# Generated by Django 3.1.2 on 2020-10-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
