# Generated by Django 3.1.2 on 2020-11-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201026_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
